### ISSUE TITLE
Getting Credentials error

### ISSUE THREAD

**Issue by Fyb3roptik** [mmontagna/zfs3backup#1]
I have both a config file (chmod 777) and env variables (for testing). It still is not working! Please help!
```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by Fyb3roptik** [comment]
I have figured this out. The README does not state WHAT to name the ENV variables. They need to be `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY` and `AWS_REGION`

**Comment by mmontagna** [comment]
Glad you got it. Yeah it uses the standard boto3 credential system.
